apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-foo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vinayakofficialgit/Kubernetes.prsl.git
    targetRevision: HEAD
    path: Installation/argocd/infra-terraform/nginx-app            ###give the path where you have deployment,svc etc
  destination:
    server: https://kubernetes.default.svc     
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true