apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-ds
  labels:
    app: monitoring-app
spec:
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80