apiVersion: v1
kind: Service
metadata:
  name: my-pod-service
  labels:
    app: my-app
  namespace: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: java
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-app