apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
  labels:
    app: xyz-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xyz-app
  template:
    metadata:
      labels:
        app: xyz-app
    spec:
      containers:
        - name: my-container
          image: mysql
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: redhat
    
